### PR TITLE
Support HACS (custom_components successor)

### LINKED ISSUE #201: Add support for HACS
Hi there

Are you going to add support to allow updating of this component using HACS instead of custom_updater as custom_updater is EOL?

### PR DESCRIPTION
**Pull request by xatr0z**
By moving the `alexa_media` into the `custom_components` directory, this plugin is able to be used within HACS.

(Note: As of now, users would still need to add https://github.com/keatontaylor/alexa_media_player/ as an repository before the integration is visible in HACS)

Resolves #201

### CODE REVIEW

**Comment by alandtse** [comment]
Thanks. Can you do 2 things?
1.  Confirm you're providing this to us under apache2 
2. Target it for dev

**Comment by alandtse** [comment]
Sorry 3 things, also edit the wiki to explain how to enable.

**Comment by xatr0z** [comment]
1. I provide this under the Apache2 license
2. You already changed to dev, thanks
3. The [wiki is updated](https://github.com/keatontaylor/alexa_media_player/wiki#hacs---home-assistant-community-store-versions--125), describnig the steps neccesary to add the repository. 
After the pull request is accepted, we could get HACS to add this plugin as an default: https://github.com/custom-components/hacs/issues/93 . This would make this extra step not needed anymore.

**Comment by xatr0z** [comment]
1. I provide this under the Apache2 license
2. You already changed to dev, thanks
3. The [wiki is updated](https://github.com/keatontaylor/alexa_media_player/wiki#hacs---home-assistant-community-store-versions--125), describnig the steps neccesary to add the repository. 
After the pull request is accepted, we could get HACS to add this plugin as an default: https://github.com/custom-components/hacs/issues/93 . This would make this extra step not needed anymore.

**Comment by alandtse** [comment]
Thanks @xatr0z for your help. I'll need to do the PR for HACS to add by default since I'm a maintainer.

**Pull request merged**
