### PR TITLE
Bluetooth Websocket 

### PR DESCRIPTION
**Pull request by keatontaylor**
Added updating bluetooth devices from WebSocket messages. Looks like for every single PUSH_BLUETOOTH_STATE_CHANGE the https://alexa.amazon.com website pulls the bluetooth state information so if they're doing it I don't think we need to mess with narrowing down the call a bit more. If we hit rate limits or users have issues we can tidy it up.

### CODE REVIEW

**Comment by alandtse** [comment]
Resolves #135

**Comment by keatontaylor** [comment]
> Generally I think this is ok. I wonder if we should reuse the update_bluetooth_state in the polling but don't think it's a big deal.
> 
> I did notice some bracket/parentheses movement. While I know we didn't conclude on pylint vs mypy, I'm pretty OCD if I see a warning in my editor and will probably revert it back the next time I make edits (assuming it triggers the warning). ;)

I think vscode got a little trigger happy with reformatting some of the line endings, feel free to change them back on your next PR.

Can you test this code just so we don't have a testing sample size of 1?

**Comment by alandtse** [comment]
I normally don't have bluetooth, but I don't see code to add new bluetooth_pairings. Is the bluetooth_state only for when a previously paired device connects?

**Comment by keatontaylor** [comment]
bluetooth_state encompasses all PUSH_BLUETOOTH_STATE_CHANGE including adding, deleting, disconnect and connect

**Comment by alandtse** [comment]
Before merging this, also merge in my fix on top #139. 

For some reason I'm not able to get the source list to dynamically update when I pair or unpair a device. I think we should investigate it.

**Pull request merged**
